# Generated by Django 5.2.11 on 2026-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('age', models.IntegerField(default=0, max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
